### ISSUE TITLE
Edit and delete User

### ISSUE THREAD

**Issue by BaptisteLegat** [FullStackMap/Back#20]
Pour le front, j'ai besoin de deux routes permettant de supprimer mon user et de le supprimer.
Pour l'édition du profil:
Un param qui est le userId
Les champs modifiable : 
_Nom, prénom, âge_

Pour le changement d'email : 
Comme pour le profil ? 
-> si oui, il faudrait envoyer un lien de confirmation sur son nouvel email pour 'confirmer' le changement
(coté front, j'ai juste 2 champs qui correspondent au nouvel email + une confirmation)

Pour le supprimer:
Un param qui est le userId
=> **_idée_**, envoyé un email de confirmation de compte avec option d'annuler la suppression du coup s'il clique sur le lien qui lui sera mis dans l'email

**Comment by Dercraker** [comment]
Oas de Nom Prénom Age juste un UserName CF https://excalidraw.com/#room=2801f4fad8f9503c60ad,jiWzsiP-U-eTB2sXkmj2Jg
